package com.dhara.gameoflife.manager;

import com.dhara.gameoflife.model.BindableBoolean;

public class StaticManager {
    public static BindableBoolean[][] getInitialStates() {
        return new BindableBoolean[][] {
                {
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false)
                },
                {
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false)
                },
                {
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false)
                },
                {
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false)
                },
                {
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(true),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false)
                },
                {
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(true),
                        new BindableBoolean(true),
                        new BindableBoolean(true),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false)
                },
                {
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(true),
                        new BindableBoolean(true),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false)
                },
                {
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false)
                },
                {
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false)
                },
                {
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false)
                },
                {
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false)
                },
                {
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false)
                },
                {
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false)
                },
                {
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false)
                },
                {
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false)
                },
                {
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false)
                },
                {
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false)
                },
                {
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false)
                },
                {
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false)
                },
                {
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false),
                        new BindableBoolean(false)
                }
        };
    }
}
